apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: cloud-service
  labels:
    app: cloud
spec:
  selector:
    app: cloud
  ports:
    - name: http
      port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: cloud-deployment
  labels:
    app: cloud
spec:
  selector:
    matchLabels:
      app: cloud
  template:
    metadata:
      labels:
        app: cloud
    spec:
      imagePullSecrets:
        - name: dzregistry
      containers:
        - image: registry.dzcardsolutions.com/cloud:latest
          name: cloud
          ports:
            - name: http
              containerPort: 80
